<?php

/** @var \Algolia\AlgoliaSearch\Block\Instant\Hit $block */

$priceKey     = $block->getPriceKey();
$currencyCode = $block->getCurrencyCode();

$baseVar         = $block->escapeHtml('price' . $priceKey);
$maxVar          = $block->escapeHtml('price' . $priceKey . '_max');
$baseFormatedVar = $block->escapeHtml('price' . $priceKey . '_formated');
$origFormatedVar = $block->escapeHtml('price' . $priceKey . '_original_formated');

?>

<script type="text/template" id="instant-hit-template">
    <div itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"> <!-- jwc -->
        <meta itemprop="position" content="{{__position}}" />
        <div class="result-wrapper" itemprop="item" itemscope itemtype="http://schema.org/Product">
            <meta itemprop="sku" content="{{sku}}" />
            <meta itemprop="mpn" content="{{mpn}}" />
            <meta itemprop="name" content="{{name}}" />
            <meta itemprop="description" content="{{short_description}}" />
            <div itemprop="brand" itemtype="https://schema.org/Brand" itemscope>
                <meta itemprop="name" content="{{manufacturer}}" />
            </div>
            <div itemprop="offers" itemtype="https://schema.org/Offer" itemscope>
                <meta itemprop="url"
                    {{^__queryID}} content="{{url}}" {{/__queryID}}
                    {{#__queryID}} content="{{urlForInsights}}" {{/__queryID}}
                />
                <meta itemprop="availability" content="{{metaAvailability}}" />
                <meta itemprop="priceCurrency" content="{{metaPriceCurrency}}" />
                <meta itemprop="itemCondition" content="{{metaCondition}}" />
                <meta itemprop="price" content="{{metaPrice}}" />
                <meta itemprop="priceValidUntil" content="{{metaPriceValidUntil}}" />
            </div>
            <a class="result"
                {{^__queryID}} href="{{url}}" {{/__queryID}}
                {{#__queryID}} href="{{urlForInsights}}" {{/__queryID}}
                data-objectid="{{objectID}}"
                data-indexname="{{__indexName}}"
                data-position="{{__position}}"
                data-queryid="{{__queryID}}"
                data-currencycode="{{currencyCode}}"
                data-category="{{category}}"
                data-items="{{items}}"
                data-impressions="{{impressions}}"> <!-- jwc -->
                <div class="result-content">
                    <div class="badges">{{#badgesLength}}<div>{{#badgesArray}}<div class="badge product-view__badge"><span>{{.}}</span></div>{{/badgesArray}}</div>{{/badgesLength}}</div> <!-- jwc -->
                    <div class="result-thumbnail">
                        {{#image_url}}<img itemprop="image" src="{{{image_url}}}" alt="{{{name}}}" />{{/image_url}}
                        {{^image_url}}<span class="no-image"></span>{{/image_url}}
                    </div>
                    <div class="result-sub-content">
                        <h3 itemprop="name" class="result-title product-title-in-list"> <!-- jwc -->
                            {{{ _highlightResult.name.value }}}
                        </h3>
                        <div class="ratings">
                            <div class="result-sub-content">
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span><?php echo __('Rating') ?>:</span></span>
                                        <div class="rating-result" title="{{rating_summary}}%">
                                            <span style="width:{{rating_summary}}%">
                                                <span>{{rating_summary}}%</span>
                                            </span>
                                        </div>
                                    </div>
                                </div>


                                {{^<?php echo $maxVar; ?>}}
                                <div itemprop="offers" itemscope itemtype="http://schema.org/Offer" class="price">
                                    <meta itemprop="price" content="{{<?php echo $baseVar; ?>}}" />
                                {{/<?php echo $maxVar; ?>}}
                                {{#<?php echo $maxVar; ?>}}
                                <div itemprop="offers" itemscope itemtype="http://schema.org/AggregateOffer" class="price">
                                    <meta itemprop="lowPrice" content="{{<?php echo $baseVar; ?>}}" />
                                    <meta itemprop="highPrice" content="{{<?php echo $maxVar; ?>}}" />
                                {{/<?php echo $maxVar; ?>}}
                                    <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>" />
                                    <div class="price-wrapper {{hidePriceClassName}}"> <!-- jwc -->
                                        <div>

                                            <span class="after_special
                                                    {{#<?php echo $origFormatedVar; ?>}}
                                                        promotion
                                                    {{/<?php echo $origFormatedVar; ?>}}">
                                                {{<?php echo $baseFormatedVar; ?>}}
                                                <sup>.{{<?php echo $block->escapeHtml('price' . $priceKey . '_formated_cents'); ?>}}</sup> <!-- jwc -->
                                            </span>
                                            {{#<?php echo $origFormatedVar; ?>}}
                                                <span class="before_special">
                                                    {{<?php echo $origFormatedVar; ?>}}
                                                </span>
                                            {{/<?php echo $origFormatedVar; ?>}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>

                        {{#isAddToCartEnabled}}
                        <form data-role="tocart-form" action="{{ addToCart.action }}" method="post">
                            <input type="hidden" name="queryID" value="{{__queryID}}">
                            <input type="hidden" name="product" value="{{objectID}}">
                            {{#_highlightResult.default_bundle_options}}<input type="hidden" name="bundle_option[{{ optionId }}]" value="{{selectionId}}">{{/_highlightResult.default_bundle_options}}
                            <input type="hidden" name="{{ addToCart.redirectUrlParam }}" value="{{ addToCart.uenc }}">
                            <input name="form_key" type="hidden" value="{{ addToCart.formKey }}">
                            <button type="submit" title="<?php echo __('Add to Cart') ?>" class="action tocart primary stock-status-button--{{inventoryavailability_primary.availability}}"
                            data-objectid="{{objectID}}"
                            data-indexname="{{__indexName}}"
                            data-position="{{__position}}"
                            data-queryid="{{__queryID}}"
                            onClick="window.addToCartOnClick(this)"
                            > <!-- jwc -->
                                <div class="hide loading-spinner loading-spinner-sm"></div> <!-- jwc -->
                                <svg class="icon" role="presentation" focusable="false"><use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shopping-cart')) ?>"></use></svg> <!-- jwc -->
                                <span><?php echo __('Add to Cart') ?></span>
                            </button>
                        </form>
                        {{/isAddToCartEnabled}}
                    </div>
                </div>
                <div class="algolia-clearfix"></div>
            </a>
            <!-- - jwc -->
            <div class="store-availability">
                <div class="dispatch-label {{inventoryavailability_primary.availability}}" data-sku="{{sku}}" onclick="showAvailabilityModal(this, 'shipping')">
                    <div class="circle"></div>
                    {{#inventoryavailability_primary.leadTimeLabel}}
                        {{inventoryavailability_primary.leadTimeLabel}}
                    {{/inventoryavailability_primary.leadTimeLabel}}
                    {{^inventoryavailability_primary.leadTimeLabel}}
                        {{inventoryavailability_primary.shortDescription}}
                    {{/inventoryavailability_primary.leadTimeLabel}}
                </div>
                <span class="check-store-availability {{inventoryavailability_primary.inStockAtJwClass}}" data-sku="{{sku}}" onclick="showAvailabilityModal(this, 'store')">
                    <svg class="icon" role="presentation" focusable="false"><use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#pin')) ?>"></use></svg>
                    <u><?php echo __('Check store availability') ?></u>
                </span>
            </div>
            <!-- + jwc -->
        </div>
    </div>
</script>

<!-- jwc -->
<?= $secureRenderer->renderTag('script', ['type' => 'text/javascript'], '
    showLoadingSpinner = (el) => {
        el.querySelector(".icon").classList.add("hide");
        el.querySelector(".loading-spinner").classList.remove("hide");
        el.setAttribute("disabled", "disabled");
        el.classList.add("disabled");
    }
    requirejs(["availability-modal"], function (availabilityModal) {
        showAvailabilityModal = (el, method) => {
            const sku = el.getAttribute("data-sku");
            availabilityModal({
                "display":method,
                "productSku":sku.indexOf(",") > -1 ? sku.split(",").shift() : sku,
            });
        }
    });
', false); ?>
<!-- jwc -->
