<?php /** @var \Algolia\AlgoliaSearch\Block\Instant\Wrapper $block */ ?>

<!-- Wrapping template -->
<script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
        <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}

    <div id="algolia_instant_selector"
         class="<?php echo $block->escapeHtml($block->hasFacets() ? ' with-facets' : ''); ?>">
        <div class="row">
            <div id="algolia-left-container"> <!-- jwc -->
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container"> <!-- jwc -->
                </div>
            </div>

            <div id="algolia-right-container"> <!-- jwc -->
                <div class="row">
                     <!-- - jwc -->
                        {{#second_bar}}
                            <div class="algolia-infos-container" id="algolia-infos-container">
                                <div class="algolia-infos-filter-wrapper">
                                    <div class="algolia-infos-current-wrapper" id="current-refinements"></div>
                                    <div class="algolia-infos-clear-wrapper" id="clear-refinements"></div>
                                </div>
                                <div id="refine-toggle" class="visible-xs visible-sm expand-filters">
                                    <?php echo $block->escapeHtml(__('Refine')); ?>
                                </div>
                                <div class="algolia-infos-search-wrapper" id="instant-search-bar">
                                    <label><?php echo $block->escapeHtml(__('Filter this page')); ?></label>
                                </div>
                                <div class="algolia-infos-stats-wrapper" id="algolia-stats"></div>
                                <div class="algolia-infos-sorts-wrapper">
                                    <div id="algolia-sorts"></div>
                                    <label><?php echo $block->escapeHtml(__('Sort by')); ?></label>
                                </div>
                            </div>
                        {{/second_bar}}
                    <!-- + jwc -->
                </div>
                <div class="row">
                    <div>  <!-- jwc -->
                        <div itemscope itemtype="http://schema.org/ItemList" class="hits">
                            <!-- jwc -->
                            <div id="algolia-banner"></div>
                            <div id="instant-empty-results-container"></div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                    <div class="algolia-clearfix"></div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>
    </div>
</script>
