<?php
/** @var \Algolia\AlgoliaSearch\ViewModel\Recommend\ProductView $block */
$viewModel = $block->getViewModel();
$recommendConfig =  $viewModel->getAlgoliaRecommendConfiguration();

if (isset($recommendConfig['enabledFBT']) || isset($recommendConfig['enabledRelated']) || isset($recommendConfig['isTrendItemsEnabledInPDP'])):
    $product = $viewModel->getProduct(); ?>
    <!-- - jwc -->
    <div class="product-recs-wrapper">
        <div id="frequentlyBoughtTogether" class="recommend-component"><div class="loading-spinner-wrapper"><div class="loading-spinner"></div></div></div>
        <div id="relatedProducts" class="recommend-component"><div class="loading-spinner-wrapper"><div class="loading-spinner"></div></div></div>
        <div id="trendItems" class="trendsItem recommend-component"><div class="loading-spinner-wrapper"><div class="loading-spinner"></div></div></div>
    </div>
    <!-- + jwc -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/recommend" : {
                    "algoliObjectId" : ["<?= $product->getId() ?>"],
                    "algoliaRecommendCartSvg": "<?php echo $block->getViewFileUrl('images/icons-sprite.svg#shopping-cart') ?>"
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php endif; ?>